/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicas.ipc1_bs12026_p1;
import javax.swing.JOptionPane;
/**
 *
 * @author alejandro
 */
public class VentanaBuscarProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaBuscarProducto.class.getName());
    private Inventario inventario;
    public VentanaBuscarProducto(Inventario inventario) {
        this.inventario = inventario;
        initComponents();
        BuscarCategoria.removeAllItems();
        BuscarCategoria.addItem("Camisa");
        BuscarCategoria.addItem("Pantalon");
        BuscarCategoria.addItem("Accesorio");
        BuscarCategoria.addItem("Otro");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BuscarNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BuscarCodigo = new javax.swing.JTextField();
        BuscarCategoria = new javax.swing.JComboBox<>();
        EjecutarBusqueda = new javax.swing.JButton();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BUSCAR PRODUCTO");

        jLabel2.setText("Nombre");

        jLabel3.setText("Codigo");

        jLabel4.setText("Categoria");

        BuscarCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EjecutarBusqueda.setText("BUSCAR");
        EjecutarBusqueda.addActionListener(this::EjecutarBusquedaActionPerformed);

        Regresar.setText("Regresar");
        Regresar.addActionListener(this::RegresarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Regresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EjecutarBusqueda))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BuscarNombre)
                            .addComponent(BuscarCodigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BuscarCategoria, 0, 144, Short.MAX_VALUE))))
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(BuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BuscarCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BuscarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EjecutarBusqueda)
                    .addComponent(Regresar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void EjecutarBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarBusquedaActionPerformed
        //octebncion de los datos obtenidos de la caja de texto
        String Codigobusqueda = BuscarCodigo.getText().trim();
        String NombreBusqueda = BuscarNombre.getText().trim();
        String CategoriaBuscar = BuscarCategoria.getSelectedItem().toString();
        boolean Econtrado =false;
        String Resultado="RESULTADOS:";
        
        if(inventario.buscarPorCodigo(Codigobusqueda)!=null){
            Econtrado=true;
            Resultado= Resultado + "\n"+inventario.buscarPorCodigo(Codigobusqueda);
        }
        if(inventario.buscarPorNombre(NombreBusqueda)!=null){
            Econtrado=true;
            Resultado= Resultado + "\n"+inventario.buscarPorNombre(NombreBusqueda);
        }
        Resultado=Resultado + "\n"+inventario.buscarPorCategoria(CategoriaBuscar);
        
        if (Econtrado) {
            JOptionPane.showMessageDialog(this, Resultado);
        }else{
            JOptionPane.showMessageDialog(this, "Producto No econtrado");
        }
        
        
        
        
    }//GEN-LAST:event_EjecutarBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //java.awt.EventQueue.invokeLater(() -> new VentanaBuscarProducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BuscarCategoria;
    private javax.swing.JTextField BuscarCodigo;
    private javax.swing.JTextField BuscarNombre;
    private javax.swing.JButton EjecutarBusqueda;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
