/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicas.ipc1_bs12026_p1;

/**
 *
 * @author alejandro
 */
public class VentanaMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaMenuPrincipal.class.getName());

    //private Producto producto;
    private Inventario inventario;
    public VentanaMenuPrincipal() {
        inventario = new Inventario(5);//capacidad de inventario para almacenar productos
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Boton_RegistrarV = new javax.swing.JButton();
        Boton_AgregarP = new javax.swing.JButton();
        Boton_BuscarP = new javax.swing.JButton();
        Boton_eliminarProducto = new javax.swing.JButton();
        Boton_VerDAtos = new javax.swing.JButton();
        Boton_GenerarRepo = new javax.swing.JButton();
        Boton_Sali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu");

        Boton_RegistrarV.setText("Registrar Venta");
        Boton_RegistrarV.addActionListener(this::Boton_RegistrarVActionPerformed);

        Boton_AgregarP.setText("Agregar Producto");
        Boton_AgregarP.addActionListener(this::Boton_AgregarPActionPerformed);

        Boton_BuscarP.setText("Buscar Producto");
        Boton_BuscarP.addActionListener(this::Boton_BuscarPActionPerformed);

        Boton_eliminarProducto.setText("Eliminar Producto");
        Boton_eliminarProducto.addActionListener(this::Boton_eliminarProductoActionPerformed);

        Boton_VerDAtos.setText("Ver Datos de estudiante");
        Boton_VerDAtos.addActionListener(this::Boton_VerDAtosActionPerformed);

        Boton_GenerarRepo.setText("Generar Reporte");
        Boton_GenerarRepo.addActionListener(this::Boton_GenerarRepoActionPerformed);

        Boton_Sali.setText("Salir");
        Boton_Sali.addActionListener(this::Boton_SaliActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Boton_RegistrarV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton_eliminarProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton_VerDAtos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton_GenerarRepo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton_Sali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton_BuscarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Boton_AgregarP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(Boton_AgregarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_BuscarP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_eliminarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_RegistrarV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_VerDAtos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_GenerarRepo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Sali)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_RegistrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RegistrarVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_RegistrarVActionPerformed

    private void Boton_AgregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AgregarPActionPerformed

        VentanaAgregarProducto ventanaAgregar= new VentanaAgregarProducto(inventario);
        ventanaAgregar.setVisible(true);
    }//GEN-LAST:event_Boton_AgregarPActionPerformed

    private void Boton_BuscarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BuscarPActionPerformed
        VentanaBuscarProducto ventanaBuscar = new VentanaBuscarProducto(inventario);
        ventanaBuscar.setVisible(true);
    }//GEN-LAST:event_Boton_BuscarPActionPerformed

    private void Boton_eliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_eliminarProductoActionPerformed
        VentanaEliminarProducto ventanaEliminar = new VentanaEliminarProducto(inventario);
        ventanaEliminar.setVisible(true);
    }//GEN-LAST:event_Boton_eliminarProductoActionPerformed

    private void Boton_VerDAtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_VerDAtosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_VerDAtosActionPerformed

    private void Boton_GenerarRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_GenerarRepoActionPerformed
        VentanaGenerarReporte ventanaReporte= new VentanaGenerarReporte(inventario);
        ventanaReporte.setVisible(true);
    }//GEN-LAST:event_Boton_GenerarRepoActionPerformed

    private void Boton_SaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_SaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Boton_SaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_AgregarP;
    private javax.swing.JButton Boton_BuscarP;
    private javax.swing.JButton Boton_GenerarRepo;
    private javax.swing.JButton Boton_RegistrarV;
    private javax.swing.JButton Boton_Sali;
    private javax.swing.JButton Boton_VerDAtos;
    private javax.swing.JButton Boton_eliminarProducto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
